# Generated by Django 3.2.20 on 2024-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
