# Generated by Django 3.2.20 on 2024-02-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_alter_transacao_data_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='pendente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='qrcode_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
