# Generated by Django 3.2.20 on 2024-02-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0005_rename_pendente_transacao_processada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='RG',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
