# Generated by Django 3.2.20 on 2024-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0006_alter_profile_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='qrcode_path',
        ),
        migrations.AddField(
            model_name='transacao',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/%d', verbose_name='QR Code'),
        ),
    ]
