# Generated by Django 3.2.20 on 2024-02-19 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0009_transacao_quantidade_cupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='valorDocumento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(50, message='O valor do documento deve ser maior que R$ 50,00 reais!')], verbose_name='Valor do Documento'),
        ),
    ]
