# Generated by Django 3.2.20 on 2024-02-20 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0010_alter_documentofiscal_valordocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='valorDocumento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(50, message='Insira um valor igual ou superior a R$ 50,00')], verbose_name='Valor do Documento'),
        ),
    ]
