# Generated by Django 3.2.20 on 2024-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0011_alter_documentofiscal_valordocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='teste')),
            ],
        ),
    ]
